language: ruby

services:
  - mysql

rvm:
  - 1.9.3

env:
  - REDMINE_VER=2.3.4

before_install:
  - export PLUGIN_NAME=redmine_default_custom_query
  - export DB=mysql
  - export REDMINE_PATH=$HOME/redmine
  - svn co http://svn.redmine.org/redmine/tags/$REDMINE_VER $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp config/database.travis.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH
  - gem install factory_girl

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake redmine:plugins:migrate

script:
  - bundle exec rake redmine:plugins:test NAME=$PLUGIN_NAME
